remote_theme: RyanFitzgerald/devportfolio
defaults:
  -
    scope:
      path: "_posts" # an empty string here means all files in the project
    values:
      layout: "post"
      type: "posts"
      author: "Jannis M."
  -
    scope:
      path: "_projects" # an empty string here means all files in the project
    values:
      layout: "pages"
